ドキュメンテーションの英語化
windChimeYK/replaceRuby pull request #70
Opened 2020-09-30 15:09 UTC by benji011

## 概要
日本語話者しか対象にしていないリポジトリー（novel-support.js）のドキュメンテーションを翻訳

## 変更
- README.md
- README_ENG.md
- docs/ns-jimdo-setup.md
- docs/ns-jimdo-setup_ENG.md

ref: https://github.com/windchime-yk/windchime-yk/issues/2

2020-10-10 07:19 UTC, windchime-yk requested changes
英語ドキュメントの追加、ありがとうございます！
確認できる範囲で気になった点を書きましたので、ご確認をお願いいたします！

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +<! -- /badge area -->
バッジ部分の表示がおかしくなっていたので、修正をお願いいたします
日本語版のREADMEのbadge areaをコピペすれば問題ないと思います

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +# novel-support.js.
パッケージ名なので、末尾のピリオドは不要かと思っています
英語に詳しくないので、訳としてピリオドなしが問題あればご指摘ください

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +[CHANGELOG.md](. /CHANGELOG.md)
リンクが死んでるので、`.`と`/`の間にある空白の削除をお願いします

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +[MIT](. /LICENSE)
リンクが死んでるので、`.`と`/`の間にある空白の削除をお願いします

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +  - Ruby notation `(| 《》 | 《》): |egg<rt>egg</rt></ruby>, rice</rt></ruby> => <ruby class="ns_ruby">egg<rt>egg<rt>egg</rt></ruby>, rice<rt>egg</rt></ruby>`.
ルビの用例として機能していないように感じたので、以下のように修正したほうがいいかと思ったのですが、いかがでしょうか
``` markdown
Ruby notation (| 《》 | 《》): |卵かけご飯《Rice with egg on top》 => `<ruby class="ns_ruby">卵かけご飯<rt>Rice with egg on top</rt></ruby>`.
```
ここだけ日本語なのは違和感あるかと思うので、よりよい用例がありましたらご教示いただければ

2020-10-10 07:19 UTC, windchime-yk commented on README_ENG.md
> +  - Circle point notation: `《《egg-over-egg rice》 => <strong class="ns_emphasis">egg-over-egg rice</strong>`
用語が統一されていなかったので、`egg-over-egg rice`を`Rice with egg on top`に修正をお願いします

2020-10-10 07:19 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> +[Whenever you want your Jimdo page to load a js file, please refer to this article](https://www.aki-nagashima.name/2014/09/17/jimdo%E3%81%A7-%E5%A4%96%E9%83%A8javascript%E3%83%95%E3%82%A1%E3%82%A4%E3
リンク先は日本語なので、訳さずに`Jimdoページにjsファイルを読み込ませたい！そんなときのあるあるメモ。`でいいと思うのですが、いかがでしょうか

2020-10-10 07:19 UTC, windchime-yk commented on docs/ns-jimdo-setup.md
> +
ドキュメントの案内は上にあったほうがいいと思うので、2行目へ移動をお願いします

2020-10-10 07:19 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> +
ドキュメントの案内は上にあったほうがいいと思うので、2行目へ移動をお願いします

2020-10-10 07:19 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> +https://github.com/windchime-yk/novel-support.js/#readme
`README_ENG.md`の末尾にDeepLへの言及があったので、もしこちらでも使われていたら追加していただければ幸いです

2020-10-10 07:40 UTC, benji011 commented
@windchime-yk 指摘ありがとうございます！たいていの部分はちょっと英訳方法わからなかったのでdeeplの力を借りて翻訳することにしました。もし他にも修正できる部分があれば教えていただけると対応致します

よろしくお願い致します！

2020-10-10 08:09 UTC, windchime-yk requested changes
@benji011 
ありがとうございます！
新規で見つけたものも含めて、気になった箇所を書きました！
ご確認をお願いいたしますー！

2020-10-10 08:09 UTC, windchime-yk commented on docs/ns-jimdo-setup.md
> +Translated with www.DeepL.com/Translator (free version)
これは`docs/ns-jimdo-setup_ENG.md`に追加をお願いします
なので、このドキュメントからは削除してください

2020-10-10 08:09 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> +Update one of the ruby tags used in your post with `||《》`.
`||《》`は`|《》`に修正をお願いいたします

2020-10-10 08:09 UTC, windchime-yk commented on README_ENG.md
> +  - Ruby notation (| 《》 | 《》): |卵かけご飯《Rice with egg on top》 => `<ruby class="ns_ruby">卵かけご飯<rt>Rice with egg on top</rt></ruby>`.rice<rt>egg</rt></ruby>`.
この行の末尾にある以下の部分が不要なので、削除をお願いします
``` markdown
.rice<rt>egg</rt></ruby>`.
```

2020-10-11 02:17 UTC, windchime-yk requested changes
@benji011 
ありがとうございますー！
1点だけ気になったことがあったので、書きました
こちら修正後にマージしようと思っております！
よろしくお願いします！

2020-10-11 02:17 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> -Update one of the ruby tags used in your post with `||《》`.
改行も合わせて消えていたので、改行の復元をお願いいたします！

2020-10-11 02:28 UTC, benji011 commented on docs/ns-jimdo-setup_ENG.md
> -Update one of the ruby tags used in your post with `||《》`.
ありがとうございます！[f567ef05cdd36fea9a60bd5a86187a512e4ba450](https://github.com/windchime-yk/novel-support.js/pull/70/commits/f567ef05cdd36fea9a60bd5a86187a512e4ba450) に改行の修正を入れましたが`ns-jimdo-setup.md`を比べてみると、改行より末尾に空白の文字)が入っていました。一応改行を入れましたがもし空白の意味でしたら修正しますけど、どう思いますか

お手数をかけいたしますがご指摘をよろしくお願い致しますｍ（＿＿）ｍ

2020-10-11 03:45 UTC, windchime-yk commented on docs/ns-jimdo-setup_ENG.md
> -Update one of the ruby tags used in your post with `||《》`.
@benji011
あー、失礼しました！ 末尾に空白が正しいです！

2020-10-11 03:50 UTC, benji011 commented on docs/ns-jimdo-setup_ENG.md
> -Update one of the ruby tags used in your post with `||《》`.
ありがとうございます！修正致しましたのでご確認をよろしくお願い致します＾＾

2020-10-11 03:53 UTC, windchime-yk approved these changes
@benji011 
ありがとうございますー！
確認しまして問題なさそうですので、こちらの内容でマージいたします！
PRしていただき、ありがとうございました！

2020-10-11 03:56 UTC, merged

2020-10-21 03:26 UTC, windchime-yk commented
@benji011 
すみません、質問なのですが、今回のPRはHacktoberfestのために行なったものですか？
私は、このパッケージが英語話者にも需要があるのかと思ってドキュメントの翻訳をマージしたのですが、イベントの参加のために翻訳したのでしたら、削除しようと思っています。

疑って申し訳ないのですが、PRが10月1日のすぐに送られていることと、貴方のステータスにHacktoberfestに参加したようなことが書かれていたため、質問した次第です。
ご回答いただければ幸いです。

2020-10-21 03:40 UTC, benji011 commented
@windchime-yk そうですね
オープンソース開発に興味を持ったのはHacktoberfestがきっかけでした。参加しているプロジェクトと参加していないものにもかかわらず興味があったのです

2020-10-21 13:17 UTC, windchime-yk commented
@benji011 
まず、刺々しい言葉を使ってしまい、申し訳ありません。
Hacktoberfestを知ったきっかけがまさにその一連の騒動で、悪印象を持っていました。その偏見が10時間前の発言につながっており、視野が狭かったことをお詫びいたします。
また、迷惑とは思っておりません。PRしていただいたこと、感謝しております。

翻訳READMEの取り扱いについてですが、そのまま残そうと思っております。
いただいたものをわざわざ消すことに、もしかしたら使うかもしれない英語話者がアクセスしづらくなるデメリットはあれど、メリットがあるとは感じられなかったためです。

突然不躾な質問をしてしまい、不快な思いもしたかもしれません。申し訳ありません。
また、PRしていただいてありがとうございました！
私もOSS開発への興味はあるものの、実際にIssueやPRを行なうのは勇気のある行動だなと感じています。今回、PRいただいたことで英語READMEが本パッケージに入ったことで、日本語READMEだからと利用を避けていた層が（もしいたら）アクセスしやすくなったと思います。ありがとうございます。

2020-10-21 23:43 UTC, benji011 commented
@windchime-yk いえいえ！こちらこそお詫び致します。正直このHacktoberfestにより私達は出だしを間違ったかもしれないです＾＾；；
今後のオープンソースに貢献させていただきたく、その中では Windchimeさんのものにも含まれると思いますのでどうぞよろしくお願い致します！